language: python
python:
  - "3.7-dev"
install:
  - pip3 install discord.py
  - pip3 install requests
  - pip3 install python-twitter
script:
  - python package_repair/discordpy_repair.py
  - python package_repair/websockets_repair.py
  - python run.py test
  - python tests/travis_run.py
