language: python
python:
  - "3.6"
  #- "3.7-dev"
install:
  - pip3 install discord.py
  - pip3 install requests
  - pip3 install python-twitter
script:
  - python tests/config_maker.py
  - python run.py test & python tests/travis_run.py
